version: '3'

services:
  api:
    build: .
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on: 
      - redis

  redis:
    image: redis:7

  worker:
    build: .
    command: celery -A main.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on: 
      - redis
      - api

  dashboard:
    build: .
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports: 
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis
      - worker

    